# Plus Resources: Django Project Starter

Deployment to Heroku / running the server after preparing for deployment runs into an error where the dj_database_url module could not be found. The most recent commit runs into that error. The previous commit (commit 76182e40786ae4ac9c48d3d804839dc148dbc471) has no issues running the server and its functionalities. 

Link to Heroku: https://fierce-crag-41898.herokuapp.com/

Please find screenshots of the working server below:

<img width="1899" alt="Index - logged out" src="https://user-images.githubusercontent.com/60630600/173223849-0b156a10-0a67-4324-830d-2d2f47d02ace.png">
<img width="1895" alt="Index - logged in" src="https://user-images.githubusercontent.com/60630600/173223852-1469b80d-fe08-4ff4-a2d5-80e8ce6b898d.png">
<img width="1905" alt="Story - logged in" src="https://user-images.githubusercontent.com/60630600/173223867-1db6364f-cfaf-48d2-93d1-b4eb75b1eedd.png">
<img width="1905" alt="Story - logged out" src="https://user-images.githubusercontent.com/60630600/173223884-b96f125d-9a26-49d2-bc16-54ce746ad935.png">
<img width="1904" alt="Submit story form" src="https://user-images.githubusercontent.com/60630600/173223900-bcb8e50e-477f-413b-b348-7d92ed79daf8.png">
<img width="1905" alt="User profile" src="https://user-images.githubusercontent.com/60630600/173223905-93490805-68ee-4fab-8025-29a748bbff4f.png">
<img width="1905" alt="Edit : delete story is user is author" src="https://user-images.githubusercontent.com/60630600/173223935-bd164987-b963-47ef-aa7f-c0a8d7153335.png">

